entryPoints:
  web:
    address: :80

providers:
  file:
    filename: /etc/traefik/dynamic.yml

experimental:
  localPlugins:
    regexTrackRedirect:
      moduleName: github.com/co-it/traefik-regex-track-redirect

log:
  level: DEBUG
